/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": process.env.REACT_APP_AWS_REGION || "us-east-1",
    "aws_cognito_identity_pool_id": process.env.REACT_APP_COGNITO_IDENTITY_POOL_ID || "us-east-1:your-identity-pool-id",
    "aws_cognito_region": process.env.REACT_APP_AWS_REGION || "us-east-1",
    "aws_user_pools_id": process.env.REACT_APP_COGNITO_USER_POOL_ID || "us-east-1_YourPool",
    "aws_user_pools_web_client_id": process.env.REACT_APP_COGNITO_CLIENT_ID || "your-client-id",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": process.env.REACT_APP_APPSYNC_ENDPOINT || "https://your-api.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": process.env.REACT_APP_AWS_REGION || "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_appsync_apiKey": process.env.REACT_APP_APPSYNC_API_KEY || "da2-fakeApiId123456",
    "aws_user_files_s3_bucket": process.env.REACT_APP_S3_BUCKET || "your-s3-bucket",
    "aws_user_files_s3_bucket_region": process.env.REACT_APP_AWS_REGION || "us-east-1",
    "aws_cloud_logic_custom": [
        {
            "name": "TimelapseAPI",
            "endpoint": process.env.REACT_APP_API_GATEWAY_ENDPOINT || "https://your-api.execute-api.us-east-1.amazonaws.com/dev",
            "region": process.env.REACT_APP_AWS_REGION || "us-east-1"
        }
    ]
};

export default awsmobile; 