/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by update_aws_config.py
// This file was generated on 2025-04-13 22:17:11

const awsmobile = {
  "aws_project_region": "us-east-1",
  "aws_cognito_identity_pool_id": "us-east-1:00000000-0000-0000-0000-000000000000",
  "aws_cognito_region": "us-east-1",
  "aws_user_pools_id": "us-east-1_XXXXXXXXX",
  "aws_user_pools_web_client_id": "0000000000000000000000000",
  "oauth": {},
  "aws_appsync_graphqlEndpoint": "https://example.appsync-api.us-east-1.amazonaws.com/graphql",
  "aws_appsync_region": "us-east-1",
  "aws_appsync_authenticationType": "API_KEY",
  "aws_user_files_s3_bucket": "timelapse-media-dev-00000000",
  "aws_user_files_s3_bucket_region": "us-east-1"
};

export default awsmobile;
